#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck disable=SC1090
. "$DIR/../lib/env.bash"
# shellcheck disable=SC1090
. "$DIR/../lib/pull.bash"

# shellcheck disable=SC2154
echo "--- :anka: Cloning $BUILDKITE_PLUGIN_ANKA_VM_NAME to $job_image_name"

if [[ "${debug_mode:-off}" =~ (on) ]] ; then
  echo "$ anka clone $BUILDKITE_PLUGIN_ANKA_VM_NAME $job_image_name" >&2
fi
anka clone "$BUILDKITE_PLUGIN_ANKA_VM_NAME" "$job_image_name"

# Support for yaml command lists: https://github.com/chef/anka-buildkite-plugin/issues/4
O_IFS=$IFS
IFS=$'\n'
mapfile -t BUILDKITE_COMMANDS < <(echo "$BUILDKITE_COMMAND")
IFS=$O_IFS
for BUILDKITE_COMMAND in "${BUILDKITE_COMMANDS[@]}"; do
  echo "+++ Executing $BUILDKITE_COMMAND in $job_image_name"
  # shellcheck disable=SC2154
  COMMAND="anka run ${args[*]} bash -c \"${BUILDKITE_COMMAND}\""
  if [[ "${debug_mode:-off}" =~ (on) ]]; then echo "$ ${COMMAND}" >&2; fi
  eval "${COMMAND}"
done
