#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck disable=SC1090,SC1091
. "$DIR/../lib/shared.bash"

BUILDKITE_PLUGIN_ANKA_POST_COMMANDS=$(plugin_read_list POST_COMMANDS)
if [[ -n "${BUILDKITE_PLUGIN_ANKA_POST_COMMANDS}" ]]; then
  host_commands=()
  while IFS='' read -r line; do host_commands+=("$line"); done <<< "$BUILDKITE_PLUGIN_ANKA_POST_COMMANDS"
  for command in "${host_commands[@]:+${host_commands[@]}}"; do
    echo "--- :anka: Executing ${command} on host"
    if [[ $(plugin_read_config DEBUG "false") =~ (true|on|1) ]] ; then
      echo -ne '\033[90m$\033[0m' >&2
      printf " %q" "eval \"$command\"" >&2
      echo >&2
    fi
    # shellcheck disable=SC2086
    eval "$command"
  done
fi